/*
 * POV_config.h
 *
 *  Created on: Jul 31, 2022
 *      Author: Mega Store
 */

#ifndef POV_CONFIG_H_
#define POV_CONFIG_H_


//#define POV_MAX_LENGTH			19

/// LEDs from center to boarder

#define POV_LED1_PORT_ID		DIO_u8_PORTA
#define POV_LED1_PIN_ID			DIO_u8_PIN0

#define POV_LED2_PORT_ID		DIO_u8_PORTA
#define POV_LED2_PIN_ID			DIO_u8_PIN1

#define POV_LED3_PORT_ID		DIO_u8_PORTA
#define POV_LED3_PIN_ID			DIO_u8_PIN2

#define POV_LED4_PORT_ID		DIO_u8_PORTA
#define POV_LED4_PIN_ID			DIO_u8_PIN3

#define POV_LED5_PORT_ID		DIO_u8_PORTA
#define POV_LED5_PIN_ID			DIO_u8_PIN4

#define POV_LED6_PORT_ID		DIO_u8_PORTA
#define POV_LED6_PIN_ID			DIO_u8_PIN5

#define POV_LED7_PORT_ID		DIO_u8_PORTA
#define POV_LED7_PIN_ID			DIO_u8_PIN6

#define POV_LED8_PORT_ID		DIO_u8_PORTA
#define POV_LED8_PIN_ID			DIO_u8_PIN7

#define POV_LED9_PORT_ID		DIO_u8_PORTC
#define POV_LED9_PIN_ID			DIO_u8_PIN0

#define POV_LED10_PORT_ID		DIO_u8_PORTC
#define POV_LED10_PIN_ID		DIO_u8_PIN1

#define POV_LED11_PORT_ID		DIO_u8_PORTC
#define POV_LED11_PIN_ID		DIO_u8_PIN2

#define POV_LED12_PORT_ID		DIO_u8_PORTC
#define POV_LED12_PIN_ID		DIO_u8_PIN3

#define POV_LED13_PORT_ID		DIO_u8_PORTC
#define POV_LED13_PIN_ID		DIO_u8_PIN4

#define POV_LED14_PORT_ID		DIO_u8_PORTC
#define POV_LED14_PIN_ID		DIO_u8_PIN5

#define POV_LED15_PORT_ID		DIO_u8_PORTC
#define POV_LED15_PIN_ID		DIO_u8_PIN6

#define POV_LED16_PORT_ID		DIO_u8_PORTC
#define POV_LED16_PIN_ID		DIO_u8_PIN7

#define POV_LED17_PORT_ID		DIO_u8_PORTB
#define POV_LED17_PIN_ID		DIO_u8_PIN0

#define POV_LED18_PORT_ID		DIO_u8_PORTB
#define POV_LED18_PIN_ID		DIO_u8_PIN1

#define POV_LED19_PORT_ID		DIO_u8_PORTB
#define POV_LED19_PIN_ID		DIO_u8_PIN2

/// arrays to make if easy to access any of them

#define POV_LEDS_PORTS_ARR	{POV_LED1_PORT_ID, POV_LED2_PORT_ID, POV_LED3_PORT_ID, POV_LED4_PORT_ID, POV_LED5_PORT_ID, POV_LED6_PORT_ID, POV_LED7_PORT_ID, POV_LED8_PORT_ID, POV_LED9_PORT_ID ,POV_LED10_PORT_ID ,POV_LED11_PORT_ID ,POV_LED12_PORT_ID ,POV_LED13_PORT_ID ,POV_LED14_PORT_ID ,POV_LED15_PORT_ID ,POV_LED16_PORT_ID ,POV_LED17_PORT_ID ,POV_LED18_PORT_ID ,POV_LED19_PORT_ID}
#define POV_LEDS_PINS_ARR	{POV_LED1_PIN_ID, POV_LED2_PIN_ID, POV_LED3_PIN_ID, POV_LED4_PIN_ID, POV_LED5_PIN_ID, POV_LED6_PIN_ID, POV_LED7_PIN_ID, POV_LED8_PIN_ID, POV_LED9_PIN_ID ,POV_LED10_PIN_ID ,POV_LED11_PIN_ID ,POV_LED12_PIN_ID ,POV_LED13_PIN_ID ,POV_LED14_PIN_ID ,POV_LED15_PIN_ID ,POV_LED16_PIN_ID ,POV_LED17_PIN_ID ,POV_LED18_PIN_ID ,POV_LED19_PIN_ID}

#endif /* POV_CONFIG_H_ */
